import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Save Forests and Heal the Climate | Stand for trees</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.container}>
        <h1>Welcome to Save Forest</h1>
        <p>
          Currently, this website is under development. Following sections are
          accessible:
        </p>
        <Link href={"/faq"} passHref>
          <a className={styles.linkStyle}>Frequently Asked Questions</a>
        </Link>
      </main>
    </div>
  );
};

export default Home;
